server:
    interface: 127.0.0.1@5554
    access-control: 127.0.0.0/8 allow
    do-daemonize: no
    verbosity: 0
    num-threads: 1
    msg-cache-size: 128m
    rrset-cache-size: 256m
    cache-max-ttl: 86400
    cache-min-ttl: 60
    do-ip6: no
    username: ""
    chroot: ""
    pidfile: "/tmp/unbound-bench.pid"
    log-queries: no
    log-replies: no
    val-log-level: 0
    module-config: "iterator"

forward-zone:
    name: "."
    forward-addr: 1.1.1.1
